# Generated by Django 5.0.3 on 2024-03-29 21:38

from django.db import migrations


INITIAL_CURRENCY_LIST = [
    'USD',
    'BRL',
    'EUR',
    'BTC',
    'ETH',
]

def populate_initial_currencies(apps, schema_editor):
    """Populate Currency table with initial data."""
    HistoricalCurrency = apps.get_model('api', 'Currency')
    HistoricalCurrency.objects.bulk_create(
        [HistoricalCurrency(acronym=acronym) for acronym in INITIAL_CURRENCY_LIST]
    )

def backward(apps, schema_editor):
    HistoricalCurrency = apps.get_model('api', 'Currency')
    HistoricalCurrency.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_currencies, backward),
    ]
